[project]
name = "test-retry"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
  "requests>=2.32.3",
  "retry>=0.9.2",
  "pytest>=8.3.5",
  "doublex>=1.9.6.1",
  "expects>=0.9.0",
  "mypy>=1.15.0",
  "ruff>=0.11.6",
]
